In [2]:
import numpy as np


In [3]:
a = np.array([[1, 0,0, -1000.8103],
               [0, 1, 0, -942.1632],
               [0, 0, 0, 1131.7119],
               [0, 0, 0.002866, -0]])

In [4]:
print(a)

[[ 1.0000000e+00  0.0000000e+00  0.0000000e+00 -1.0008103e+03]
 [ 0.0000000e+00  1.0000000e+00  0.0000000e+00 -9.4216320e+02]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  1.1317119e+03]
 [ 0.0000000e+00  0.0000000e+00  2.8660000e-03  0.0000000e+00]]


In [8]:
disparity = np.array([[845.8],[1082.6],[1082.6-837.4],[1]])

In [12]:
coor = np.dot(a, disparity)
coor = coor/coor[3][0]

In [13]:
coor

array([[-2.20578869e+02],
       [ 1.99840852e+02],
       [ 1.61042028e+03],
       [ 1.00000000e+00]])

In [3]:
rotation = np.array([[-0.49973541, 0.075331509, -0.86289608],
 [-0.86593741, -0.019968279, 0.49975353],
 [0.02041664, 0.99695861, 0.075211234]])
print(rotation)

[[-0.49973541  0.07533151 -0.86289608]
 [-0.86593741 -0.01996828  0.49975353]
 [ 0.02041664  0.99695861  0.07521123]]


In [61]:
vec0 = np.matrix([0.80521357, -0.56181872, 0.18971217])
vec1 = np.matrix([-0.077859268, 0.21698944, 0.97306406])
np.cross(vec0, vec1)

array([[-0.58785114, -0.79829524,  0.13098005]])

In [4]:
transform = np.array([[293.183807, -263.036957, -1065.503662]]).T

In [7]:
vec = np.array([[-77.570457, 337.332886, 1370.142822]]).T


In [8]:
print(np.dot(rotation, vec+ transform)) 

[[-365.0247384 ]
 [ -35.94673211]
 [ 101.3843534 ]]


In [53]:
0.97**2+0.22**2+0.08**2

0.9956999999999999

In [2]:
1/(2*3.14159*5)

0.03183101550488765

In [17]:
from math import atan2
for x in range(-10, 10):
    for y in range(0, 10):
        print("({0},{1}): atan {2} ".format(y, -x, atan2(y,-x)/3.14159*180))

(0,10): atan 0.0 
(1,10): atan 5.710597961035388 
(2,10): atan 11.30994202711956 
(3,10): atan 16.699258339253717 
(4,10): atan 21.80142790123017 
(5,10): atan 26.565073615635743 
(6,10): atan 30.963782686061883 
(7,10): atan 34.992049755078654 
(8,10): atan 38.65984090866073 
(9,10): atan 41.9872479609278 
(0,9): atan 0.0 
(1,9): atan 6.340197101245298 
(2,9): atan 12.528818291791593 
(3,9): atan 18.43496439427029 
(4,9): atan 23.962509214843838 
(5,9): atan 29.054628640472068 
(6,9): atan 33.690095982786474 
(7,9): atan 37.87501564275531 
(8,9): atan 41.63357450294615 
(9,9): atan 45.000038009906035 
(0,8): atan 0.0 
(1,8): atan 7.125022367150729 
(2,8): atan 14.03625532384415 
(3,8): atan 20.55606258254674 
(4,8): atan 26.565073615635743 
(5,8): atan 32.00541024189702 
(6,8): atan 36.86992878854058 
(7,8): atan 41.185959954001774 
(8,8): atan 45.000038009906035 
(9,8): atan 48.36650151686592 
(0,7): atan 0.0 
(1,7): atan 8.130109221365458 
(2,7): atan 15.94540936943396 
(3,7): atan 

In [16]:
atan2(10, -10)*180/3.14159

135.0001140297181

In [11]:
import scipy.io as scio
import os
from os.path import dirname
import numpy  as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import normalize

mat_file = 'f.mat'
yml_file = 'camera_calib.yml'

In [15]:
mat_data = scio.loadmat(mat_file)
print(mat_data.keys())
print(mat_data['mat'])


dict_keys(['__header__', '__version__', '__globals__', 'mat', '__function_workspace__'])
[[(MatlabOpaque([(b'', b'MCOS', b'stereoParameters', array([[3707764736],
       [         2],
       [         1],
       [         1],
       [         1],
       [         4]], dtype=uint32))],
             dtype=[('s0', 'O'), ('s1', 'O'), ('s2', 'O'), ('arr', 'O')]),)]]
